"""
Risk classification tool for AI agents.
"""
import pandas as pd

from src.models.rules_engine import evaluate_all
from src.models.hybrid_scorer import score_all_customers

def classify_risk(transactions_df: pd.DataFrame, features_with_ml: pd.DataFrame, pattern_focus: str | None = None) -> pd.DataFrame:
    """
    Evaluates heuristic rules and combines them with ML anomaly scores for a final risk level.
    
    Args:
        transactions_df: DataFrame containing raw transaction history.
        features_with_ml: DataFrame containing features + 'iso_forest_score' column 
                          (generated by detect_anomalies tool).
        pattern_focus: Optional rule name to isolate evaluation (e.g., 'structuring').
                          
    Returns:
        pd.DataFrame: A per-customer risk summary including risk_level, final_score, 
                      and triggered_rules.
    """
    if transactions_df.empty or features_with_ml.empty:
        return pd.DataFrame()
        
    # 1. Filter out insignificant background noise prior to rule evaluation 
    # to maintain strict calibration and prevent false-positive floods.
    significant_txns = transactions_df[transactions_df["amount"] >= 8000].copy()
    
    # 2. Evaluate deterministic heuristic rules
    rule_names = [pattern_focus] if pattern_focus else None
    rule_results_by_customer = evaluate_all(significant_txns, rule_names=rule_names)
    
    # 3. Hybridize ML scores with Rule overrides
    risk_summary_df = score_all_customers(transactions_df, features_with_ml, rule_results_by_customer)
    
    return risk_summary_df
